# Generated by Django 5.2.7 on 2025-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (auto-generated)')),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Avatar URL or Path')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography (supports Markdown/HTML)')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
