# Generated by Django 5.2.7 on 2025-11-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_attachments/', verbose_name='PDF文件')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='文件描述')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_attachments', to='posts.post')),
            ],
            options={
                'verbose_name': 'PDF附件',
                'verbose_name_plural': 'PDF附件',
            },
        ),
    ]
